protocol = "mks-multigas-2030"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-mks"
bugtracker = "https://github.com/yaq-project/yaqd-mks/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-mks"

[config]

[state]

[messages]

